import { SupplementCategory } from './types';

export const supplementCategories: SupplementCategory[] = [
  {
    id: 'vitaminC',
    name: '비타민 C',
    emoji: '🍊',
    color: 'from-orange-400 to-yellow-400',
    description: '면역력 강화와 피부 미용에 필수적인 항산화 비타민',
    benefits: ['면역력 강화', '피부 콜라겐 합성', '항산화 작용', '피로 회복'],
    targetConcerns: ['immunity', 'skin', 'fatigue', 'dry_skin'],
    pharmacyProducts: [
      {
        id: 'vc-ph-1',
        name: '고려은단 비타민C 1000 이지스왈로우',
        brand: '고려은단',
        price: 12900,
        description: '비타민C 1000mg 고함량, 삼키기 편한 소프트 타입',
        features: ['1000mg 고함량', '소프트 타입', '합성착색료 무첨가', '500정 대용량'],
        rating: 4.6,
        reviewCount: 3240,
        reviews: [
          { author: '김민지', rating: 5, content: '오랫동안 먹어온 제품이에요. 가격도 합리적이고 알약 크기도 작아서 삼키기 편해요. 감기에 잘 안 걸리는 것 같아요!', date: '2024-11-15' },
          { author: '박서준', rating: 4, content: '약국에서 쉽게 구할 수 있고 믿을 수 있는 브랜드예요. 매일 챙겨 먹고 있습니다.', date: '2024-10-22' },
          { author: '이수연', rating: 5, content: '피부가 밝아진 것 같아요. 2달 정도 꾸준히 먹었더니 확실히 차이가 나네요.', date: '2024-09-30' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'vc-ph-2',
        name: '유한양행 헬시비타 비타민C 500',
        brand: '유한양행',
        price: 8500,
        description: '하루 2정으로 비타민C 1000mg 충족, 경제적인 선택',
        features: ['국내 제약사 생산', '순수 비타민C', '100정', 'GMP 인증'],
        rating: 4.4,
        reviewCount: 1870,
        reviews: [
          { author: '최현우', rating: 5, content: '유한양행이라 믿고 먹어요. 부작용 없이 잘 맞고 있습니다.', date: '2024-11-01' },
          { author: '정다은', rating: 4, content: '가격 대비 품질이 좋아요. 약국 상담사 추천으로 구매했는데 만족합니다.', date: '2024-10-15' },
          { author: '강지훈', rating: 4, content: '소화도 잘 되고 냄새도 없어서 좋아요.', date: '2024-09-20' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'vc-ph-3',
        name: '일양약품 비타민C 파워',
        brand: '일양약품',
        price: 10500,
        description: '비타민C + 아연 복합 설계로 면역력 이중 강화',
        features: ['비타민C + 아연 복합', '240정', '면역력 강화', '국내 제조'],
        rating: 4.3,
        reviewCount: 980,
        reviews: [
          { author: '윤소희', rating: 4, content: '아연이 같이 들어있어서 면역력에 더 효과적인 것 같아요.', date: '2024-11-10' },
          { author: '한승민', rating: 4, content: '약사님이 추천해주셔서 먹기 시작했는데 확실히 기력이 좋아진 느낌이에요.', date: '2024-10-05' },
          { author: '임나영', rating: 5, content: '피로감이 줄었어요. 꾸준히 먹을 것 같습니다.', date: '2024-09-15' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'vc-mk-1',
        name: 'NOW Foods Vitamin C-1000 with Rose Hips',
        brand: 'NOW Foods',
        price: 19800,
        description: '로즈힙 천연 비타민C 함유, 250정 대용량',
        features: ['로즈힙 함유', '250정', 'Non-GMO', 'GMP 인증'],
        rating: 4.8,
        reviewCount: 8500,
        reviews: [
          { author: '송유진', rating: 5, content: '미국 직구템인데 정말 좋아요. 알약 크기도 적당하고 위장 자극도 없어요. 쿠팡에서 편하게 살 수 있어서 자주 주문해요.', date: '2024-11-18' },
          { author: '오준혁', rating: 5, content: '미국에서 유명한 브랜드라고 해서 사봤는데 확실히 흡수가 잘 되는 느낌이에요. 피부도 좋아졌어요.', date: '2024-10-30' },
          { author: '배민정', rating: 4, content: '가격은 국산보다 비싸지만 품질 면에서 만족해요. 로즈힙까지 들어있으니 더 좋은 것 같아요.', date: '2024-10-08' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'vc-mk-2',
        name: 'Solgar Vitamin C 1000mg with Rose Hips',
        brand: 'Solgar',
        price: 32000,
        description: '프리미엄 비타민C, 식물성 소재 사용',
        features: ['비건 인증', '글루텐 프리', '식물성 캡슐', '90정'],
        rating: 4.7,
        reviewCount: 4200,
        reviews: [
          { author: '김지아', rating: 5, content: '솔가는 역시 믿을 수 있는 브랜드예요. 흡수율이 다른 것들보다 좋다는 느낌이에요.', date: '2024-11-05' },
          { author: '이도현', rating: 4, content: '가격이 좀 있긴 하지만 비건이고 품질 좋아서 계속 먹고 있어요.', date: '2024-10-20' },
          { author: '조수민', rating: 5, content: '면역력이 좋아진 것 같아요. 올겨울은 감기 한 번도 안 걸렸어요!', date: '2024-09-25' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'vc-mk-3',
        name: 'Nature Made Vitamin C 1000mg',
        brand: 'Nature Made',
        price: 16500,
        description: 'USP 인증 고흡수 비타민C, 300정 대용량 경제적',
        features: ['USP 인증', '300정', '글루텐 프리', '타임 릴리즈'],
        rating: 4.6,
        reviewCount: 5600,
        reviews: [
          { author: '최수영', rating: 5, content: 'USP 인증 제품이라 믿음이 가요. 가격도 합리적이고 양도 많아서 오래 먹을 수 있어요.', date: '2024-11-12' },
          { author: '박진우', rating: 4, content: '자주 사던 브랜드인데 역시 실망 없어요.', date: '2024-10-28' },
          { author: '류지수', rating: 5, content: '피로 회복에 도움이 되는 것 같아요. 타임 릴리즈라 하루 종일 유지되는 것 같고요.', date: '2024-09-18' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'vitaminD',
    name: '비타민 D',
    emoji: '☀️',
    color: 'from-yellow-400 to-amber-500',
    description: '뼈 건강과 면역력의 핵심, 실내 생활자에게 특히 필요',
    benefits: ['뼈 건강 강화', '면역력 증진', '우울감 개선', '칼슘 흡수 촉진'],
    targetConcerns: ['immunity', 'bones', 'fatigue', 'stress'],
    pharmacyProducts: [
      {
        id: 'vd-ph-1',
        name: '종근당 비타민D3 2000IU',
        brand: '종근당',
        price: 9800,
        description: '적정 용량 2000IU, 180정 장기 복용 가능',
        features: ['2000IU', '180정 대용량', 'GMP 인증', '국내 제조'],
        rating: 4.7,
        reviewCount: 2450,
        reviews: [
          { author: '김태영', rating: 5, content: '종근당이라 믿고 먹어요. 재구매 수십 번 했네요.', date: '2024-11-14' },
          { author: '이미래', rating: 5, content: '겨울에 특히 챙겨 먹는 필수 영양제예요. 우울감도 줄어든 것 같아요.', date: '2024-10-25' },
          { author: '박호준', rating: 4, content: '알약이 작고 냄새도 없어요. 꾸준히 먹을 수 있는 제품이에요.', date: '2024-10-02' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'vd-ph-2',
        name: '한미약품 비타민D 1000IU 츄어블',
        brand: '한미약품',
        price: 7500,
        description: '달콤한 레몬 맛 씹어 먹는 비타민D, 어린이도 OK',
        features: ['레몬향 츄어블', '1000IU', '90정', '어린이 가능'],
        rating: 4.5,
        reviewCount: 1380,
        reviews: [
          { author: '신채원', rating: 5, content: '아이와 같이 먹을 수 있어서 좋아요. 맛도 좋고 아이가 먼저 달라고 해요.', date: '2024-11-08' },
          { author: '고민준', rating: 4, content: '씹어 먹는 거라 삼키기 어려운 분들도 편하게 드실 수 있어요.', date: '2024-10-18' },
          { author: '장혜진', rating: 4, content: '맛도 좋고 효과도 있는 것 같아요. 계속 재구매할 것 같아요.', date: '2024-09-27' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'vd-ph-3',
        name: '광동제약 비타민D3+K2',
        brand: '광동제약',
        price: 14500,
        description: '비타민D3와 K2 복합으로 칼슘을 뼈로 유도',
        features: ['D3+K2 복합', '뼈 건강 최적화', '60정', '식물성 원료'],
        rating: 4.4,
        reviewCount: 860,
        reviews: [
          { author: '문지원', rating: 5, content: 'K2가 같이 들어있어서 뼈에 더 효과적이라고 해요. 골다공증 예방 차원에서 먹고 있어요.', date: '2024-11-02' },
          { author: '손준서', rating: 4, content: '약사님이 D3+K2 조합을 추천해주셔서 샀어요. 든든하게 먹고 있습니다.', date: '2024-10-12' },
          { author: '홍나은', rating: 4, content: '허리가 좋아진 것 같아요. 꾸준히 먹어봐야 알겠지만 기대가 돼요.', date: '2024-09-22' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'vd-mk-1',
        name: 'NOW Foods Vitamin D3 5000 IU',
        brand: 'NOW Foods',
        price: 14000,
        description: '고함량 5000IU, 240정 대용량 실속형',
        features: ['5000IU 고함량', '240정', 'Non-GMO', '소프트젤'],
        rating: 4.8,
        reviewCount: 12400,
        reviews: [
          { author: '안시현', rating: 5, content: '미국 직구 제품 중에 제일 신뢰가 가는 브랜드예요. 가격도 저렴하고 용량도 많아요.', date: '2024-11-20' },
          { author: '백도윤', rating: 5, content: '병원에서 비타민D 수치 낮다고 해서 이걸로 3개월 먹었더니 정상 범위로 올라왔어요!', date: '2024-10-31' },
          { author: '남지영', rating: 4, content: '소프트젤 타입이라 삼키기 편하고 복통도 없어요.', date: '2024-10-10' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'vd-mk-2',
        name: 'Nature Made Vitamin D3 2000 IU',
        brand: 'Nature Made',
        price: 18500,
        description: 'USP 인증, 파마코피아 기준 충족 안전한 비타민D',
        features: ['USP 인증', '2000IU', '260정', '글루텐 프리'],
        rating: 4.7,
        reviewCount: 7800,
        reviews: [
          { author: '임현석', rating: 5, content: 'USP 인증 받은 제품이라 성분 믿을 수 있어요. 꾸준히 먹고 있어요.', date: '2024-11-07' },
          { author: '서가은', rating: 4, content: '무난하게 좋아요. 미국 약국에서도 판매되는 제품이라 믿음이 가요.', date: '2024-10-23' },
          { author: '권태현', rating: 5, content: '겨울 내내 챙겨 먹었더니 컨디션이 많이 좋아졌어요.', date: '2024-09-28' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'vd-mk-3',
        name: 'Thorne Research Vitamin D/K2',
        brand: 'Thorne Research',
        price: 38000,
        description: '임상 등급 D3+K2 복합, 최고급 흡수율',
        features: ['D3+K2 복합', '글루텐/유제품 프리', '임상 등급', '소프트젤 60정'],
        rating: 4.9,
        reviewCount: 3100,
        reviews: [
          { author: '정승현', rating: 5, content: '손꼽는 프리미엄 브랜드예요. 가격이 좀 있지만 품질은 확실해요. 뼈 건강에 투자하는 셈이에요.', date: '2024-11-16' },
          { author: '최아진', rating: 5, content: '의사한테 추천받은 브랜드예요. 흡수가 잘 되는지 컨디션이 정말 좋아졌어요.', date: '2024-10-27' },
          { author: '황민철', rating: 4, content: '가격이 비싸서 망설였지만 효과가 있어서 계속 사고 있어요.', date: '2024-10-05' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'omega3',
    name: '오메가 3',
    emoji: '🐟',
    color: 'from-blue-400 to-cyan-500',
    description: '혈관 건강과 뇌 기능 개선, 염증 억제의 핵심 지방산',
    benefits: ['혈관 건강', '뇌 기능 향상', '염증 억제', '중성지방 감소'],
    targetConcerns: ['cardiovascular', 'bones', 'stress', 'fatigue'],
    pharmacyProducts: [
      {
        id: 'om-ph-1',
        name: '동원 덴마크 오메가3',
        brand: '동원F&B',
        price: 22000,
        description: '덴마크산 정제 어유, EPA+DHA 고함량 함유',
        features: ['EPA+DHA 고함량', '60캡슐', '정제 어유', '비린맛 최소화'],
        rating: 4.5,
        reviewCount: 1950,
        reviews: [
          { author: '김성민', rating: 5, content: '비린내가 거의 없어요. 오메가3 먹다가 비린 맛에 포기했었는데 이건 괜찮아요.', date: '2024-11-11' },
          { author: '이주현', rating: 4, content: '콜레스테롤 관리 차원에서 먹고 있어요. 3개월 먹고 검사하니 수치가 좋아졌어요.', date: '2024-10-24' },
          { author: '박예진', rating: 4, content: '캡슐이 너무 크지 않아서 삼키기 편해요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'om-ph-2',
        name: '유한양행 오메가3 트리플',
        brand: '유한양행',
        price: 18500,
        description: 'EPA+DHA 합계 900mg 고함량, 30일분',
        features: ['EPA+DHA 900mg', '60정', '코팅 캡슐', '위장 보호'],
        rating: 4.4,
        reviewCount: 1230,
        reviews: [
          { author: '최준영', rating: 5, content: '국내 제약사 제품이라 안심하고 먹어요. 효과도 느끼고 있어요.', date: '2024-11-04' },
          { author: '정미현', rating: 4, content: '코팅이 되어 있어서 뱃속에서 녹아 비린내가 없어요. 좋아요.', date: '2024-10-16' },
          { author: '강민혁', rating: 4, content: '가격 대비 품질이 괜찮아요.', date: '2024-09-26' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'om-ph-3',
        name: '일동제약 오메가3 세라마이드',
        brand: '일동제약',
        price: 25000,
        description: '오메가3 + 세라마이드 복합, 피부까지 케어',
        features: ['오메가3 + 세라마이드', '피부 건강', '60정', 'EPA+DHA'],
        rating: 4.3,
        reviewCount: 720,
        reviews: [
          { author: '신예원', rating: 4, content: '세라마이드까지 들어 있어서 피부에도 좋더라고요. 두 가지 효과를 한 번에.', date: '2024-11-06' },
          { author: '고준혁', rating: 5, content: '피부가 촉촉해진 것 같아요. 오메가3 먹으면서 피부 효과도 보고 있어요.', date: '2024-10-20' },
          { author: '장서연', rating: 4, content: '조금 비싸지만 복합 효과가 있어서 만족해요.', date: '2024-09-30' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'om-mk-1',
        name: 'Nordic Naturals Ultimate Omega',
        brand: 'Nordic Naturals',
        price: 45000,
        description: '세계 1위 오메가3 브랜드, 초고순도 분자 증류',
        features: ['EPA+DHA 1280mg', '60소프트젤', 'NSF 인증', '트라이글리세리드 형태'],
        rating: 4.9,
        reviewCount: 25000,
        reviews: [
          { author: '윤도연', rating: 5, content: '오메가3 최고 브랜드예요. 품질이 다릅니다. 비린내도 전혀 없고 흡수율도 좋아요. 비싸도 이걸 계속 살 것 같아요.', date: '2024-11-19' },
          { author: '오현서', rating: 5, content: '의사 선생님이 이 브랜드 추천해주셔서 먹기 시작했어요. 중성지방 수치가 많이 좋아졌어요.', date: '2024-10-29' },
          { author: '배준호', rating: 4, content: '가격이 부담되지만 이것도 투자라고 생각해요. 품질이 확실히 달라요.', date: '2024-10-07' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'om-mk-2',
        name: 'NOW Foods Ultra Omega-3',
        brand: 'NOW Foods',
        price: 22000,
        description: '500 EPA / 250 DHA 고함량, 합리적인 가격',
        features: ['EPA 500mg / DHA 250mg', '100소프트젤', 'IFOS 인증', 'Non-GMO'],
        rating: 4.7,
        reviewCount: 9800,
        reviews: [
          { author: '류민준', rating: 5, content: '가성비 최고예요. IFOS 인증까지 받은 제품인데 이 가격이면 대박이에요.', date: '2024-11-09' },
          { author: '임수현', rating: 4, content: '무난하게 좋아요. 비린내 없고 알약도 삼키기 편해요.', date: '2024-10-21' },
          { author: '서태양', rating: 5, content: '가격 대비 품질이 최고예요. 계속 재구매 중이에요.', date: '2024-09-29' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'om-mk-3',
        name: 'Garden of Life Minami Omega-3',
        brand: 'Garden of Life',
        price: 35000,
        description: '소형 알약으로 복용 편리, 어류 콜라겐 함유',
        features: ['작은 소프트젤', 'EPA+DHA 850mg', '60정', '비린내 없음'],
        rating: 4.6,
        reviewCount: 5200,
        reviews: [
          { author: '권나현', rating: 5, content: '알약이 정말 작아서 삼키기 너무 편해요. 오메가3가 크기 때문에 먹기 싫었는데 이건 달라요.', date: '2024-11-13' },
          { author: '황지수', rating: 4, content: '냄새도 없고 위장 자극도 없어서 좋아요.', date: '2024-10-26' },
          { author: '정우진', rating: 5, content: '처음 먹는 오메가3로 추천하는 제품이에요. 먹기 편하고 효과도 좋아요.', date: '2024-10-04' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'probiotics',
    name: '유산균',
    emoji: '🦠',
    color: 'from-green-400 to-emerald-500',
    description: '장 건강의 핵심, 소화 개선과 면역력 강화의 기초',
    benefits: ['소화 개선', '장 환경 개선', '면역력 강화', '변비/설사 완화'],
    targetConcerns: ['digestive', 'immunity', 'constipation'],
    pharmacyProducts: [
      {
        id: 'pr-ph-1',
        name: '일동제약 비오비타 리얼 유산균',
        brand: '일동제약',
        price: 16800,
        description: '100억 CFU 보장, 냉장 보관 불필요 상온 유지',
        features: ['100억 CFU', '30포', '상온 보관', '복합 유산균 19종'],
        rating: 4.6,
        reviewCount: 3100,
        reviews: [
          { author: '김소연', rating: 5, content: '변비가 심했는데 2주 만에 눈에 띄게 좋아졌어요. 장이 편해진 느낌이에요.', date: '2024-11-15' },
          { author: '이준호', rating: 4, content: '냉장 보관 안 해도 돼서 편해요. 여행 갈 때도 가져갈 수 있어서 좋아요.', date: '2024-10-25' },
          { author: '박현진', rating: 5, content: '소화가 훨씬 잘 되고 배가 편해요. 꾸준히 먹을 것 같아요.', date: '2024-10-02' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'pr-ph-2',
        name: 'CJ웰케어 헛개나무 프로젝트 쾌변',
        brand: 'CJ웰케어',
        price: 14500,
        description: '유산균 + 식이섬유 + 헛개나무 복합, 쾌변 특화',
        features: ['유산균 + 식이섬유', '헛개나무 함유', '30포', '변비 특화'],
        rating: 4.4,
        reviewCount: 2250,
        reviews: [
          { author: '최민아', rating: 4, content: '변비로 오래 고생했는데 이걸 먹고 많이 좋아졌어요. 식이섬유까지 같이 들어있어서 효과적인 것 같아요.', date: '2024-11-07' },
          { author: '정도현', rating: 5, content: '장운동이 활발해진 것 같아요. 쾌변이라는 이름처럼 효과가 있어요.', date: '2024-10-19' },
          { author: '강나연', rating: 4, content: '맛도 괜찮고 효과도 있어요.', date: '2024-09-28' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'pr-ph-3',
        name: '한독 에스더포뮬러 리얼 유산균 골드',
        brand: '한독',
        price: 22000,
        description: '더블 코팅으로 위산 통과율 극대화, 장까지 살아서 도달',
        features: ['더블 코팅', '30캡슐', '50억 보장균수', '장까지 생존'],
        rating: 4.5,
        reviewCount: 1680,
        reviews: [
          { author: '윤지수', rating: 5, content: '코팅이 되어있어서 위산에 녹지 않고 장까지 살아서 간다고 해요. 실제로 효과가 있는 것 같아요.', date: '2024-11-03' },
          { author: '오민재', rating: 4, content: '가격이 조금 있지만 확실히 효과 있어요.', date: '2024-10-15' },
          { author: '배수진', rating: 4, content: '장 건강이 많이 좋아졌어요. 꾸준히 먹을 것 같습니다.', date: '2024-09-23' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'pr-mk-1',
        name: 'Culturelle Digestive Daily Probiotic',
        brand: 'Culturelle',
        price: 28000,
        description: '세계 1위 유산균 브랜드, LGG 균주 100억 CFU',
        features: ['LGG 균주', '100억 CFU', '30캡슐', '글루텐/유제품 프리'],
        rating: 4.8,
        reviewCount: 18000,
        reviews: [
          { author: '류수아', rating: 5, content: '세계에서 가장 많이 팔린다는 유산균이에요. 실제로 먹어보니 소화가 엄청 좋아졌어요. 배가 항상 불편했는데 이걸 먹고 나서 많이 편해졌어요.', date: '2024-11-18' },
          { author: '임진서', rating: 5, content: 'IBS 증상이 있는데 먹고 나서 많이 좋아졌어요. 가스도 줄고 소화도 잘 돼요.', date: '2024-10-30' },
          { author: '서지훈', rating: 4, content: '가격이 좀 있지만 확실히 효과가 있어요. 꾸준히 먹을 것 같아요.', date: '2024-10-08' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'pr-mk-2',
        name: 'Garden of Life Raw Probiotics',
        brand: 'Garden of Life',
        price: 42000,
        description: '생유산균 34종 850억 CFU, 냉장 보관 프리미엄',
        features: ['34종 복합 균주', '850억 CFU', '90캡슐', '냉장 보관'],
        rating: 4.7,
        reviewCount: 6500,
        reviews: [
          { author: '권현주', rating: 5, content: '34종이나 들어있어요. 확실히 장이 편해진 것 같아요. 가격은 비싸지만 품질은 최고예요.', date: '2024-11-10' },
          { author: '황재민', rating: 4, content: '냉장 보관이 필요해서 좀 불편하지만 그만큼 생균이라 효과가 좋아요.', date: '2024-10-22' },
          { author: '정나연', rating: 5, content: '면역력도 올라가고 소화도 잘 돼요. 추천합니다.', date: '2024-09-30' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'pr-mk-3',
        name: 'Renew Life Ultimate Flora Probiotic',
        brand: 'Renew Life',
        price: 34000,
        description: '50억~1000억 CFU 다양한 옵션, 과민성 대장 증후군 특화',
        features: ['12종 균주', '300억 CFU', '30캡슐', '장용 코팅'],
        rating: 4.6,
        reviewCount: 8900,
        reviews: [
          { author: '안준우', rating: 5, content: '과민성 대장 증후군으로 고생했는데 많이 좋아졌어요. 강력 추천!', date: '2024-11-14' },
          { author: '백서영', rating: 4, content: '장이 예민한 분들께 추천해요. 먹고 나서 배가 편해졌어요.', date: '2024-10-26' },
          { author: '남현수', rating: 5, content: '꾸준히 먹은지 3개월 됐는데 확실히 장 건강이 좋아졌어요.', date: '2024-10-03' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'magnesium',
    name: '마그네슘',
    emoji: '⚡',
    color: 'from-purple-400 to-violet-500',
    description: '300여 가지 효소 반응에 관여, 수면·근육·신경 건강의 핵심',
    benefits: ['수면 질 개선', '근육 경련 완화', '스트레스 감소', '뼈 건강 지원'],
    targetConcerns: ['stress', 'bones', 'muscle_cramp', 'fatigue'],
    pharmacyProducts: [
      {
        id: 'mg-ph-1',
        name: '고려은단 마그네슘 플러스',
        brand: '고려은단',
        price: 11800,
        description: '마그네슘 + 비타민B6 복합, 신경 건강 시너지',
        features: ['마그네슘 + 비타민B6', '60정', '신경 건강', 'GMP 인증'],
        rating: 4.5,
        reviewCount: 1840,
        reviews: [
          { author: '김지민', rating: 5, content: '다리에 쥐가 자주 났는데 먹고 나서 거의 없어졌어요. 수면도 훨씬 깊어진 것 같아요.', date: '2024-11-16' },
          { author: '이현우', rating: 4, content: 'B6까지 들어있어서 신경 건강에 더 효과적인 것 같아요.', date: '2024-10-27' },
          { author: '박수진', rating: 5, content: '자기 전에 먹으면 숙면에 도움이 돼요. 진짜 효과 있어요.', date: '2024-10-04' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'mg-ph-2',
        name: '유한양행 마그네슘 액상',
        brand: '유한양행',
        price: 13500,
        description: '흡수가 빠른 액상 마그네슘, 포 타입으로 편리',
        features: ['액상 타입', '빠른 흡수', '30포', '레몬 맛'],
        rating: 4.4,
        reviewCount: 980,
        reviews: [
          { author: '최태원', rating: 5, content: '알약 못 삼키는 분들께 추천이에요. 맛도 있고 흡수도 빨라요.', date: '2024-11-05' },
          { author: '정수빈', rating: 4, content: '물에 타서 마시니까 편하고 효과도 좋아요.', date: '2024-10-17' },
          { author: '강예진', rating: 4, content: '맛이 좋아서 매일 챙겨 먹게 돼요.', date: '2024-09-27' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'mg-ph-3',
        name: '종근당 마그네슘 칼슘 아연',
        brand: '종근당',
        price: 15000,
        description: '마그네슘+칼슘+아연 3중 복합으로 뼈 건강 올인원',
        features: ['마그네슘+칼슘+아연 복합', '120정', '뼈/근육 건강', 'GMP 인증'],
        rating: 4.6,
        reviewCount: 2100,
        reviews: [
          { author: '윤재현', rating: 5, content: '세 가지가 한 번에 들어 있어서 편해요. 뼈 건강 걱정되는 분들께 추천!', date: '2024-11-12' },
          { author: '오가은', rating: 4, content: '종근당이라 믿고 사요. 꾸준히 먹고 있어요.', date: '2024-10-23' },
          { author: '배현민', rating: 5, content: '관절이 많이 편해졌어요. 오래 먹어야 효과가 나오는 것 같아요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'mg-mk-1',
        name: 'Doctor\'s Best High Absorption Magnesium',
        brand: "Doctor's Best",
        price: 18000,
        description: '킬레이트 마그네슘으로 흡수율 극대화',
        features: ['킬레이트 형태', '200mg x 240정', 'Non-GMO', '글루텐 프리'],
        rating: 4.9,
        reviewCount: 32000,
        reviews: [
          { author: '류나현', rating: 5, content: '마그네슘 중에 최고예요. 킬레이트 형태라 흡수가 정말 잘 돼요. 먹고 나서 수면 질이 확실히 달라졌어요.', date: '2024-11-20' },
          { author: '임도현', rating: 5, content: '다리 경련이 완전히 없어졌어요. 이 제품 최고입니다.', date: '2024-10-31' },
          { author: '서주연', rating: 4, content: '가격 대비 양이 많고 효과도 좋아요.', date: '2024-10-09' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'mg-mk-2',
        name: 'Natural Vitality CALM Magnesium',
        brand: 'Natural Vitality',
        price: 32000,
        description: '파우더 타입 마그네슘, 스트레스 완화 특화',
        features: ['파우더 타입', '스트레스 완화', '225g (약 30일분)', '레몬 라즈베리 맛'],
        rating: 4.7,
        reviewCount: 15000,
        reviews: [
          { author: '권민수', rating: 5, content: '파우더라 물에 녹여 마시는데 맛이 엄청 좋아요. 저녁에 마시면 진짜 스트레스가 풀리고 잠이 잘 와요.', date: '2024-11-08' },
          { author: '황수진', rating: 4, content: '불안감이 줄어드는 것 같아요. 스트레스 받는 분들께 추천!', date: '2024-10-21' },
          { author: '정기현', rating: 5, content: '맛도 있고 효과도 좋아요. 재구매 여러 번 했어요.', date: '2024-09-30' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'mg-mk-3',
        name: 'NOW Foods Magnesium Glycinate',
        brand: 'NOW Foods',
        price: 22000,
        description: '글리시네이트 형태로 위장 자극 최소화',
        features: ['글리시네이트 형태', '100mg x 180정', '위장 친화적', 'Non-GMO'],
        rating: 4.7,
        reviewCount: 11000,
        reviews: [
          { author: '안지현', rating: 5, content: '위장이 약한 분들도 편하게 먹을 수 있어요. 위자극 없고 흡수도 잘 돼요.', date: '2024-11-15' },
          { author: '백재원', rating: 4, content: '글리시네이트 형태가 최고로 흡수 잘 된다고 해서 샀어요. 좋아요.', date: '2024-10-27' },
          { author: '남서연', rating: 5, content: '수면 질이 많이 좋아졌어요. 꿈도 잘 안 꾸고 깊이 자요.', date: '2024-10-05' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'zinc',
    name: '아연',
    emoji: '🔬',
    color: 'from-teal-400 to-cyan-500',
    description: '면역·피부·탈모 예방의 필수 미네랄',
    benefits: ['면역력 강화', '피부 건강', '탈모 예방', '상처 치유'],
    targetConcerns: ['immunity', 'skin', 'hair_loss', 'dry_skin'],
    pharmacyProducts: [
      {
        id: 'zn-ph-1',
        name: '종근당 아연 15mg',
        brand: '종근당',
        price: 8500,
        description: '하루 적정 섭취량 100% 충족, 소형 알약',
        features: ['아연 15mg', '90정', '소형 알약', 'GMP 인증'],
        rating: 4.5,
        reviewCount: 1620,
        reviews: [
          { author: '김민서', rating: 5, content: '탈모 예방으로 먹기 시작했어요. 3개월 후에 확실히 머리가 덜 빠지는 것 같아요.', date: '2024-11-14' },
          { author: '이준서', rating: 4, content: '면역력에 좋다고 해서 먹고 있어요. 감기도 잘 안 걸리는 것 같아요.', date: '2024-10-24' },
          { author: '박지현', rating: 4, content: '가격도 싸고 효과도 있는 것 같아요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'zn-ph-2',
        name: '한미약품 아연+셀레늄',
        brand: '한미약품',
        price: 11200,
        description: '아연 + 셀레늄 복합 항산화 시너지',
        features: ['아연+셀레늄 복합', '항산화', '60정', '국내 제조'],
        rating: 4.4,
        reviewCount: 890,
        reviews: [
          { author: '최지훈', rating: 4, content: '셀레늄까지 같이 들어있어서 더 효과적인 것 같아요. 피부도 좋아졌어요.', date: '2024-11-06' },
          { author: '정하은', rating: 5, content: '탈모가 고민이었는데 많이 줄어들었어요. 효과 확실히 있어요.', date: '2024-10-18' },
          { author: '강유진', rating: 4, content: '국내 제약사라 믿고 먹어요.', date: '2024-09-28' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'zn-ph-3',
        name: '고려은단 아연 멀티비타민',
        brand: '고려은단',
        price: 14800,
        description: '아연 포함 12가지 비타민 미네랄 올인원',
        features: ['12가지 영양소', '비타민+미네랄', '60정', '종합 영양제'],
        rating: 4.3,
        reviewCount: 2400,
        reviews: [
          { author: '윤민호', rating: 4, content: '이거 하나로 여러 영양소 한 번에 챙겨요. 편리해서 좋아요.', date: '2024-11-10' },
          { author: '오수연', rating: 4, content: '면역력이 전체적으로 좋아진 것 같아요.', date: '2024-10-22' },
          { author: '배준혁', rating: 5, content: '꾸준히 먹으니까 컨디션이 유지되는 것 같아요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'zn-mk-1',
        name: 'Thorne Research Zinc Picolinate',
        brand: 'Thorne Research',
        price: 26000,
        description: '피콜리네이트 형태로 최고 흡수율, 임상 등급',
        features: ['피콜리네이트 형태', '최고 흡수율', '30mg x 60캡슐', 'NSF 인증'],
        rating: 4.9,
        reviewCount: 7800,
        reviews: [
          { author: '류재민', rating: 5, content: '흡수율이 다른 아연 제품들과 비교가 안 돼요. 탈모에 확실한 효과를 봤어요.', date: '2024-11-17' },
          { author: '임소연', rating: 5, content: '의사한테 추천받은 브랜드예요. 효과가 빠르게 나타났어요.', date: '2024-10-28' },
          { author: '서민준', rating: 4, content: '비싸지만 확실히 차이 있어요.', date: '2024-10-06' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'zn-mk-2',
        name: 'NOW Foods Zinc 50mg',
        brand: 'NOW Foods',
        price: 12000,
        description: '글루콘산 아연 고함량, 가성비 최강',
        features: ['50mg 고함량', '글루콘산 아연', '250정', 'Non-GMO'],
        rating: 4.7,
        reviewCount: 14000,
        reviews: [
          { author: '권지나', rating: 5, content: '가격이 저렴한데 양도 많고 효과도 좋아요. 재구매 계속 하고 있어요.', date: '2024-11-11' },
          { author: '황도연', rating: 4, content: '면역력 강화 목적으로 먹고 있는데 확실히 효과 있는 것 같아요.', date: '2024-10-24' },
          { author: '정미라', rating: 5, content: '피부도 좋아지고 탈모도 줄었어요. 강력 추천!', date: '2024-10-02' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'zn-mk-3',
        name: 'Solgar Zinc 22mg',
        brand: 'Solgar',
        price: 18000,
        description: '글루콘산/피콜리네이트 복합 아연, 비건 인증',
        features: ['비건 인증', '글루텐 프리', '22mg', '100정'],
        rating: 4.7,
        reviewCount: 5600,
        reviews: [
          { author: '안현지', rating: 5, content: '솔가는 역시 믿을 수 있어요. 비건이라 더 좋고 효과도 있어요.', date: '2024-11-13' },
          { author: '백민준', rating: 4, content: '피부가 깨끗해진 것 같아요. 여드름도 줄었어요.', date: '2024-10-25' },
          { author: '남예지', rating: 4, content: '꾸준히 먹으면 효과가 나와요.', date: '2024-10-03' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'lutein',
    name: '루테인',
    emoji: '👁️',
    color: 'from-yellow-500 to-green-400',
    description: '황반 보호와 눈 피로 완화, 디지털 기기 과사용 시대의 필수 영양소',
    benefits: ['황반 보호', '눈 피로 완화', '블루라이트 차단', '시력 보호'],
    targetConcerns: ['eyes', 'blurry_vision'],
    pharmacyProducts: [
      {
        id: 'lu-ph-1',
        name: '한미약품 아이케어 루테인 20mg',
        brand: '한미약품',
        price: 18000,
        description: '루테인 20mg + 지아잔틴 복합, 눈 건강 최적화',
        features: ['루테인 20mg + 지아잔틴', '30정', '황반 보호', 'GMP 인증'],
        rating: 4.6,
        reviewCount: 2150,
        reviews: [
          { author: '김재원', rating: 5, content: '눈이 항상 뻑뻑했는데 먹고 나서 많이 편해졌어요. 컴퓨터 일 오래 하시는 분들께 추천!', date: '2024-11-16' },
          { author: '이수진', rating: 4, content: '지아잔틴까지 들어있어서 더 효과적인 것 같아요.', date: '2024-10-27' },
          { author: '박현수', rating: 5, content: '눈 피로가 많이 줄었어요. 화면 보는 시간이 긴 분들께 필수예요.', date: '2024-10-04' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'lu-ph-2',
        name: '유한양행 루테인 골드 10mg',
        brand: '유한양행',
        price: 15500,
        description: '마리골드 꽃에서 추출한 천연 루테인, 소화 편한 소프트젤',
        features: ['천연 루테인', '10mg', '60정', '소프트젤 타입'],
        rating: 4.4,
        reviewCount: 1380,
        reviews: [
          { author: '최하준', rating: 4, content: '천연 추출이라 더 믿음이 가요. 눈이 시원해진 느낌이에요.', date: '2024-11-08' },
          { author: '정유진', rating: 5, content: '소프트젤이라 삼키기 편하고 효과도 좋아요.', date: '2024-10-20' },
          { author: '강현민', rating: 4, content: '꾸준히 먹고 있어요. 눈 건강에 도움이 되는 것 같아요.', date: '2024-09-29' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'lu-ph-3',
        name: '동화약품 루테인 아스타잔틴',
        brand: '동화약품',
        price: 22000,
        description: '루테인 + 아스타잔틴 강력 항산화 이중 눈 보호',
        features: ['루테인+아스타잔틴', '강력 항산화', '30캡슐', '눈 피로 특화'],
        rating: 4.5,
        reviewCount: 980,
        reviews: [
          { author: '윤서진', rating: 5, content: '아스타잔틴까지 같이 들어있어서 눈 피로가 정말 빨리 풀려요. 게임을 오래 해도 눈이 덜 피로해요.', date: '2024-11-12' },
          { author: '오지우', rating: 4, content: '눈이 많이 편해졌어요. 눈 충혈도 줄었고요.', date: '2024-10-23' },
          { author: '배예린', rating: 4, content: '효과가 좋아요. 계속 재구매하고 있어요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'lu-mk-1',
        name: 'NOW Foods Lutein 20mg with Zeaxanthin',
        brand: 'NOW Foods',
        price: 18500,
        description: '루테인 20mg + 지아잔틴 1mg, 황반 보호 최적 비율',
        features: ['루테인 20mg', '지아잔틴 1mg', '90소프트젤', 'Non-GMO'],
        rating: 4.8,
        reviewCount: 9200,
        reviews: [
          { author: '류민혁', rating: 5, content: '눈이 엄청 피로했는데 확실히 좋아졌어요. 황반 비율까지 최적화되어 있어서 믿음이 가요.', date: '2024-11-19' },
          { author: '임지수', rating: 4, content: '가격 대비 양이 많고 효과도 좋아요.', date: '2024-10-30' },
          { author: '서도연', rating: 5, content: '재구매 중이에요. 눈 건강 필수템이에요.', date: '2024-10-08' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'lu-mk-2',
        name: "Doctor's Best Lutein with OptiLut",
        brand: "Doctor's Best",
        price: 25000,
        description: '임상 검증된 OptiLut 루테인, 생체이용률 극대화',
        features: ['OptiLut 루테인', '10mg x 60정', '임상 검증', 'Non-GMO'],
        rating: 4.8,
        reviewCount: 6100,
        reviews: [
          { author: '권재현', rating: 5, content: 'OptiLut라는 특허 성분이라 흡수율이 달라요. 눈이 정말 편해졌어요.', date: '2024-11-11' },
          { author: '황수현', rating: 4, content: '임상 검증 제품이라 믿음이 가요. 효과도 좋고요.', date: '2024-10-23' },
          { author: '정우현', rating: 5, content: '눈 침침함이 많이 줄었어요. 강력 추천합니다.', date: '2024-10-02' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'lu-mk-3',
        name: 'Solgar Advanced Eye Support',
        brand: 'Solgar',
        price: 48000,
        description: '종합 눈 건강 포뮬러: 루테인+지아잔틴+빌베리+비타민A',
        features: ['4중 복합', '60정', '빌베리 추출물', '비건 인증'],
        rating: 4.7,
        reviewCount: 3800,
        reviews: [
          { author: '안지민', rating: 5, content: '여러 성분이 같이 들어있어서 눈 건강을 통합적으로 케어해줘요. 가격은 좀 있지만 가장 효과가 좋아요.', date: '2024-11-15' },
          { author: '백지수', rating: 4, content: '빌베리까지 들어있어서 야간 시력도 좋아진 것 같아요.', date: '2024-10-26' },
          { author: '남도현', rating: 5, content: '눈 건강 올인원으로 최고예요.', date: '2024-10-04' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'collagen',
    name: '콜라겐',
    emoji: '✨',
    color: 'from-pink-400 to-rose-500',
    description: '피부 탄력과 관절 건강을 동시에 케어하는 단백질',
    benefits: ['피부 탄력 개선', '관절 건강', '피부 수분', '주름 감소'],
    targetConcerns: ['skin', 'dry_skin', 'bones'],
    pharmacyProducts: [
      {
        id: 'co-ph-1',
        name: 'CJ웰케어 온 피부 콜라겐 5000mg',
        brand: 'CJ웰케어',
        price: 19800,
        description: '저분자 콜라겐 5000mg 고함량, 30포 스틱 타입',
        features: ['저분자 콜라겐 5000mg', '30포', '복숭아 맛', '흡수율 최적화'],
        rating: 4.6,
        reviewCount: 2800,
        reviews: [
          { author: '김나연', rating: 5, content: '피부가 확실히 촉촉해졌어요. 2개월 먹었더니 주변에서 피부 좋아졌다고 해요.', date: '2024-11-17' },
          { author: '이수아', rating: 4, content: '맛도 있고 효과도 좋아요. 저분자라 흡수가 잘 되는 것 같아요.', date: '2024-10-28' },
          { author: '박나현', rating: 5, content: '탄력이 좋아진 것 같아요. 계속 재구매하고 있어요.', date: '2024-10-06' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'co-ph-2',
        name: '종근당 뷰티 콜라겐 이너뷰티',
        brand: '종근당',
        price: 24500,
        description: '콜라겐 + 히알루론산 + 비타민C 트리플 피부 케어',
        features: ['콜라겐+히알루론산+비타민C', '30포', '피부 수분', '이너뷰티'],
        rating: 4.5,
        reviewCount: 1950,
        reviews: [
          { author: '최수민', rating: 5, content: '세 가지가 한 번에! 피부가 촉촉하고 탄력 있어졌어요. 히알루론산까지 들어있어서 더 좋아요.', date: '2024-11-09' },
          { author: '정예원', rating: 4, content: '맛도 좋고 피부 효과도 확실히 있어요.', date: '2024-10-21' },
          { author: '강민지', rating: 5, content: '피부가 달라졌다는 걸 느껴요. 꾸준히 먹고 있어요.', date: '2024-09-30' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'co-ph-3',
        name: '한독 에스더포뮬러 피쉬 콜라겐',
        brand: '한독',
        price: 28000,
        description: '어류에서 추출한 마린 콜라겐, 흡수율 높은 펩타이드 형태',
        features: ['마린 콜라겐', '펩타이드 형태', '30정', '관절+피부 동시'],
        rating: 4.4,
        reviewCount: 1100,
        reviews: [
          { author: '윤지아', rating: 4, content: '마린 콜라겐이 흡수가 더 잘 된다고 해서 샀어요. 확실히 피부가 좋아진 것 같아요.', date: '2024-11-04' },
          { author: '오준혁', rating: 5, content: '무릎 관절에도 좋다고 해서 먹고 있어요. 움직임이 많이 편해졌어요.', date: '2024-10-16' },
          { author: '배지수', rating: 4, content: '가격 대비 효과 좋아요.', date: '2024-09-25' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'co-mk-1',
        name: 'Vital Proteins Collagen Peptides',
        brand: 'Vital Proteins',
        price: 55000,
        description: '세계 1위 콜라겐 브랜드, 무맛 파우더로 어디에나 첨가',
        features: ['콜라겐 펩타이드', '283g (약 28일분)', '무맛/무취', '커피에 첨가 가능'],
        rating: 4.8,
        reviewCount: 45000,
        reviews: [
          { author: '류예진', rating: 5, content: '세계에서 가장 많이 팔리는 콜라겐이에요. 커피에 넣어 먹는데 맛도 안 변하고 피부가 정말 좋아졌어요. 외국 여행 가서 미국인들 피부 좋은 이유가 이것 때문인 것 같아요.', date: '2024-11-20' },
          { author: '임가현', rating: 5, content: '피부 탄력이 돌아왔어요. 3개월 꾸준히 먹었더니 확실히 달라요.', date: '2024-10-31' },
          { author: '서민지', rating: 4, content: '가격이 좀 있지만 효과가 확실해요.', date: '2024-10-09' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'co-mk-2',
        name: 'Sports Research Collagen Peptides',
        brand: 'Sports Research',
        price: 38000,
        description: '초저분자 가수분해 콜라겐, 운동과 피부 동시 케어',
        features: ['초저분자 가수분해', '454g', 'Non-GMO', 'NSF 인증'],
        rating: 4.8,
        reviewCount: 28000,
        reviews: [
          { author: '권수빈', rating: 5, content: 'Vital Proteins보다 가격도 저렴하고 품질도 비슷해요. 재구매 계속 하고 있어요.', date: '2024-11-13' },
          { author: '황지현', rating: 4, content: '피부도 좋아지고 운동 후 회복도 빨라진 것 같아요.', date: '2024-10-25' },
          { author: '정재민', rating: 5, content: '가성비 최고예요. 이 가격에 이 품질이면 최고죠.', date: '2024-10-03' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'co-mk-3',
        name: 'Garden of Life Grass Fed Collagen',
        brand: 'Garden of Life',
        price: 48000,
        description: '목초사육 소 유래 콜라겐, 비오틴 추가 함유',
        features: ['목초사육 소 유래', '비오틴 함유', '12g x 20포', '무첨가물'],
        rating: 4.7,
        reviewCount: 8500,
        reviews: [
          { author: '안민아', rating: 5, content: '목초사육이라 더 깨끗한 원료예요. 비오틴까지 들어있어서 머리카락도 좋아진 것 같아요.', date: '2024-11-16' },
          { author: '백주연', rating: 4, content: '청정 원료를 사용해서 믿음이 가요.', date: '2024-10-27' },
          { author: '남진우', rating: 5, content: '피부가 환해진 것 같아요. 계속 먹을 것 같아요.', date: '2024-10-05' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'iron',
    name: '철분',
    emoji: '🩸',
    color: 'from-red-400 to-rose-600',
    description: '빈혈 예방과 에너지 생산의 핵심 미네랄, 특히 채식주의자·여성에게 중요',
    benefits: ['빈혈 예방', '에너지 생산', '산소 운반', '피로 회복'],
    targetConcerns: ['fatigue', 'hair_loss', 'vegetarian'],
    pharmacyProducts: [
      {
        id: 'ir-ph-1',
        name: '유한양행 훼로바-유 서방정',
        brand: '유한양행',
        price: 6800,
        description: '서방형으로 위장 자극 최소화, 40년 역사 국민 철분제',
        features: ['서방형 철분', '위장 친화적', '30정', '30년 이상 판매'],
        rating: 4.7,
        reviewCount: 4200,
        reviews: [
          { author: '김소영', rating: 5, content: '임신 중에 의사 선생님이 추천해주신 제품이에요. 철분제 먹으면 속이 안 좋았는데 이건 괜찮아요.', date: '2024-11-17' },
          { author: '이정원', rating: 5, content: '빈혈 있어서 먹고 있어요. 어지럼증이 많이 줄었어요.', date: '2024-10-28' },
          { author: '박유진', rating: 4, content: '국민 철분제라 믿고 먹어요. 효과 좋아요.', date: '2024-10-06' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'ir-ph-2',
        name: '일동제약 퍼팩트 아이언 비타민C',
        brand: '일동제약',
        price: 12500,
        description: '철분 + 비타민C 복합으로 흡수율 2배 향상',
        features: ['철분+비타민C 복합', '30정', '흡수율 2배', '빈혈 특화'],
        rating: 4.5,
        reviewCount: 1680,
        reviews: [
          { author: '최아현', rating: 5, content: '비타민C가 같이 들어있어서 철분 흡수가 훨씬 잘 돼요. 빈혈 수치가 빨리 좋아졌어요.', date: '2024-11-11' },
          { author: '정민서', rating: 4, content: '속이 안 불편하고 잘 맞아요.', date: '2024-10-23' },
          { author: '강지민', rating: 5, content: '혈색이 좋아졌다고 주변에서 그러더라고요.', date: '2024-10-01' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'ir-ph-3',
        name: '한미약품 철분 엽산 임산부 영양제',
        brand: '한미약품',
        price: 15000,
        description: '철분 + 엽산 + 비타민B12 임산부 최적화',
        features: ['철분+엽산+B12', '임산부 추천', '30정', '위장 보호 코팅'],
        rating: 4.6,
        reviewCount: 2350,
        reviews: [
          { author: '윤하은', rating: 5, content: '임신 중에 먹고 있어요. 세 가지가 한 번에 들어있어서 편해요.', date: '2024-11-08' },
          { author: '오지현', rating: 4, content: '엽산까지 같이 챙길 수 있어서 좋아요.', date: '2024-10-20' },
          { author: '배민아', rating: 5, content: '임신 초기부터 계속 먹고 있어요. 속도 안 불편하고 좋아요.', date: '2024-09-29' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'ir-mk-1',
        name: 'Thorne Research Iron Bisglycinate',
        brand: 'Thorne Research',
        price: 32000,
        description: '비스글리시네이트 형태로 위장 자극 거의 없음, 최고 흡수율',
        features: ['비스글리시네이트 형태', '25mg x 60정', '위장 친화적', 'NSF 인증'],
        rating: 4.9,
        reviewCount: 8900,
        reviews: [
          { author: '류나현', rating: 5, content: '철분제 먹으면 항상 속이 안 좋았는데 이건 전혀 불편하지 않아요. 빈혈도 빨리 개선됐어요.', date: '2024-11-18' },
          { author: '임수민', rating: 5, content: '의사 선생님이 추천해주신 브랜드예요. 흡수율이 높아서 효과가 빨리 나타났어요.', date: '2024-10-29' },
          { author: '서예진', rating: 4, content: '가격이 있지만 위장 자극 없는 제품이 이거 밖에 없어요.', date: '2024-10-07' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'ir-mk-2',
        name: 'Solgar Gentle Iron 25mg',
        brand: 'Solgar',
        price: 24000,
        description: '순한 철분, 변비 없는 신개념 철분제',
        features: ['젠틀 아이언', '변비 예방', '90정', '비건 인증'],
        rating: 4.8,
        reviewCount: 12000,
        reviews: [
          { author: '권지수', rating: 5, content: '철분제 먹으면 변비가 심해져서 포기했었는데 이건 괜찮아요. 정말 순해요.', date: '2024-11-12' },
          { author: '황민정', rating: 4, content: '비건이라 더 좋고 부작용도 없어요.', date: '2024-10-24' },
          { author: '정지우', rating: 5, content: '빈혈 수치가 빨리 올라왔어요. 속도 안 불편하고 완전 만족해요.', date: '2024-10-02' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'ir-mk-3',
        name: 'NOW Foods Iron 18mg',
        brand: 'NOW Foods',
        price: 11000,
        description: '18mg 적정 용량, 글루콘산 철 가성비 제품',
        features: ['18mg 적정 용량', '글루콘산 철', '120정', 'Non-GMO'],
        rating: 4.6,
        reviewCount: 7800,
        reviews: [
          { author: '안소현', rating: 5, content: '가성비 최고예요. 양도 많고 가격도 저렴하고 효과도 있어요.', date: '2024-11-14' },
          { author: '백지현', rating: 4, content: '무난하게 좋아요. 빈혈 수치 올리는 데 도움이 됐어요.', date: '2024-10-26' },
          { author: '남수진', rating: 5, content: '피로감이 많이 줄었어요. 꾸준히 먹을 것 같아요.', date: '2024-10-04' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
  {
    id: 'milkThistle',
    name: '밀크씨슬',
    emoji: '🌿',
    color: 'from-green-500 to-teal-600',
    description: '간 건강의 핵심, 음주·약물·스트레스로 지친 간 보호',
    benefits: ['간 보호', '해독 작용', '간 세포 재생', '숙취 완화'],
    targetConcerns: ['fatigue', 'stress'],
    pharmacyProducts: [
      {
        id: 'mt-ph-1',
        name: '동화약품 밀크씨슬 70%',
        brand: '동화약품',
        price: 16800,
        description: '실리마린 70% 고함량 추출, 간 보호 강화',
        features: ['실리마린 70%', '60정', '간 보호 강화', 'GMP 인증'],
        rating: 4.6,
        reviewCount: 2100,
        reviews: [
          { author: '김현수', rating: 5, content: '술을 자주 마셔서 간이 걱정돼서 먹기 시작했어요. 확실히 다음 날 컨디션이 달라요.', date: '2024-11-15' },
          { author: '이재환', rating: 4, content: '동화약품이라 믿고 먹어요. 피로감이 줄어든 것 같아요.', date: '2024-10-26' },
          { author: '박도현', rating: 5, content: '간 수치가 높아서 의사 선생님이 밀크씨슬 추천해주셔서 먹고 있어요.', date: '2024-10-04' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'mt-ph-2',
        name: '종근당 실리마린 밀크씨슬',
        brand: '종근당',
        price: 19500,
        description: '실리마린 130mg 함량, 30일분 1일 2정 복용',
        features: ['실리마린 130mg', '60정', '간 세포 보호', '국내 제조'],
        rating: 4.5,
        reviewCount: 1680,
        reviews: [
          { author: '최민석', rating: 5, content: '종근당 믿고 먹어요. 피로가 줄어들었고 간 수치도 좋아졌어요.', date: '2024-11-09' },
          { author: '정수현', rating: 4, content: '꾸준히 먹으니 컨디션이 좋아진 것 같아요.', date: '2024-10-21' },
          { author: '강재민', rating: 4, content: '가격 대비 효과 좋아요.', date: '2024-09-30' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
      {
        id: 'mt-ph-3',
        name: '한독 밀크씨슬 레귤러',
        brand: '한독',
        price: 14000,
        description: '경제적인 가격의 실리마린 기본 복용 제품',
        features: ['실리마린 표준 함량', '30정', '경제적', '국내 제조'],
        rating: 4.3,
        reviewCount: 920,
        reviews: [
          { author: '윤준서', rating: 4, content: '가격이 저렴해서 매일 챙겨 먹기 좋아요.', date: '2024-11-06' },
          { author: '오민준', rating: 4, content: '간 건강 유지 목적으로 꾸준히 먹고 있어요.', date: '2024-10-18' },
          { author: '배서연', rating: 4, content: '무난하게 좋아요.', date: '2024-09-27' },
        ],
        type: 'pharmacy',
        imageEmoji: '💊',
      },
    ],
    marketplaceProducts: [
      {
        id: 'mt-mk-1',
        name: 'NOW Foods Silymarin Milk Thistle Extract',
        brand: 'NOW Foods',
        price: 20000,
        description: '실리마린 80% 표준화 추출, 150mg 고함량',
        features: ['실리마린 80%', '150mg x 120정', 'Non-GMO', '글루텐 프리'],
        rating: 4.8,
        reviewCount: 11000,
        reviews: [
          { author: '류재원', rating: 5, content: '실리마린 80%로 농축되어 있어서 효과가 강력해요. 간 수치 개선에 확실히 도움이 됐어요.', date: '2024-11-19' },
          { author: '임지혁', rating: 5, content: '가격 대비 품질이 최고예요. 120정이나 들어있어서 오래 먹을 수 있어요.', date: '2024-10-30' },
          { author: '서나연', rating: 4, content: '술을 자주 마시는 분들께 강력 추천해요.', date: '2024-10-08' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'mt-mk-2',
        name: 'Jarrow Formulas Milk Thistle',
        brand: 'Jarrow Formulas',
        price: 28000,
        description: '30:1 농축 추출물, Silybin Phytosome® 특허 기술',
        features: ['Silybin Phytosome® 특허', '30:1 농축', '60정', '생체이용률 4-5배'],
        rating: 4.9,
        reviewCount: 15000,
        reviews: [
          { author: '권민혁', rating: 5, content: '특허 기술로 일반 밀크씨슬보다 흡수율이 4-5배 높다고 해요. 실제로 효과가 확실히 달랐어요.', date: '2024-11-13' },
          { author: '황소연', rating: 5, content: '간이 정말 안 좋았는데 이걸 먹고 3개월 후 수치가 정상으로 돌아왔어요.', date: '2024-10-25' },
          { author: '정현우', rating: 4, content: '비싼 만큼 효과가 확실해요. 계속 재구매할 것 같아요.', date: '2024-10-03' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
      {
        id: 'mt-mk-3',
        name: 'Solgar Milk Thistle Herb Extract',
        brand: 'Solgar',
        price: 35000,
        description: '솔가 프리미엄 밀크씨슬, 표준화 실리마린 보장',
        features: ['표준화 실리마린', '비건 인증', '50정', '글루텐 프리'],
        rating: 4.7,
        reviewCount: 5200,
        reviews: [
          { author: '안재현', rating: 5, content: '솔가는 역시 품질이 달라요. 간 건강이 많이 좋아진 것 같아요.', date: '2024-11-16' },
          { author: '백수현', rating: 4, content: '비건 인증이라 더 좋아요. 효과도 만족스러워요.', date: '2024-10-27' },
          { author: '남태현', rating: 5, content: '꾸준히 먹은 보람이 있어요. 피로감이 줄고 컨디션이 좋아졌어요.', date: '2024-10-05' },
        ],
        type: 'marketplace',
        link: 'https://www.coupang.com',
        imageEmoji: '🛒',
      },
    ],
  },
];

export function getCategoryById(id: string): SupplementCategory | undefined {
  return supplementCategories.find((cat) => cat.id === id);
}
